/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.lorengie.Interface;

/**
 *
 * @author ANDRES
 */
public class IntDealer extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz10
     */
    public IntDealer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlInter10 = new javax.swing.JPanel();
        lblTittle10 = new javax.swing.JLabel();
        lblDealer = new javax.swing.JLabel();
        lblDealerImg = new javax.swing.JLabel();
        lblListImg = new javax.swing.JLabel();
        lblAddImg = new javax.swing.JLabel();
        lblCheckImg = new javax.swing.JLabel();
        btnRegisOrderDeliver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlInter10.setBackground(new java.awt.Color(204, 204, 255));

        lblTittle10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Lorengie.png"))); // NOI18N

        lblDealer.setText("Dealer");

        lblDealerImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Dealer.JPG"))); // NOI18N

        lblListImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/list.JPG"))); // NOI18N

        lblAddImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Add.JPG"))); // NOI18N

        lblCheckImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Check.JPG"))); // NOI18N

        btnRegisOrderDeliver.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRegisOrderDeliver.setText("Register Order Delivered");
        btnRegisOrderDeliver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisOrderDeliverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlInter10Layout = new javax.swing.GroupLayout(pnlInter10);
        pnlInter10.setLayout(pnlInter10Layout);
        pnlInter10Layout.setHorizontalGroup(
            pnlInter10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInter10Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblTittle10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addGroup(pnlInter10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDealerImg)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlInter10Layout.createSequentialGroup()
                        .addComponent(lblDealer)
                        .addGap(14, 14, 14)))
                .addGap(33, 33, 33))
            .addGroup(pnlInter10Layout.createSequentialGroup()
                .addGap(208, 208, 208)
                .addGroup(pnlInter10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRegisOrderDeliver, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlInter10Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(lblListImg)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblAddImg)
                        .addGap(18, 18, 18)
                        .addComponent(lblCheckImg, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlInter10Layout.setVerticalGroup(
            pnlInter10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInter10Layout.createSequentialGroup()
                .addGroup(pnlInter10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlInter10Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(lblDealer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDealerImg))
                    .addGroup(pnlInter10Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTittle10)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlInter10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlInter10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblListImg)
                        .addComponent(lblCheckImg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlInter10Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lblAddImg, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(45, 45, 45)
                .addComponent(btnRegisOrderDeliver, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlInter10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlInter10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegisOrderDeliverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisOrderDeliverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegisOrderDeliverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IntDealer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IntDealer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IntDealer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IntDealer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IntDealer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegisOrderDeliver;
    private javax.swing.JLabel lblAddImg;
    private javax.swing.JLabel lblCheckImg;
    private javax.swing.JLabel lblDealer;
    private javax.swing.JLabel lblDealerImg;
    private javax.swing.JLabel lblListImg;
    private javax.swing.JLabel lblTittle10;
    private javax.swing.JPanel pnlInter10;
    // End of variables declaration//GEN-END:variables
}
