package com.lorengie.Interface;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author ASUS_
 */
public class IntDeliveryRegister extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz5
     */
    public IntDeliveryRegister() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlDeliveryRegister = new javax.swing.JPanel();
        lblDelReg = new javax.swing.JLabel();
        lblDateTime = new javax.swing.JLabel();
        lblDelAdd = new javax.swing.JLabel();
        lblNameRec = new javax.swing.JLabel();
        btnRegDel = new javax.swing.JButton();
        txtDateTime = new javax.swing.JTextField();
        txtDelAdd = new javax.swing.JTextField();
        txtNameRec = new javax.swing.JTextField();
        pnlDelivery = new javax.swing.JPanel();
        jspDelReg = new javax.swing.JScrollPane();
        tblDelReg = new javax.swing.JTable();
        lblNameRec1 = new javax.swing.JLabel();
        txtNameRec1 = new javax.swing.JTextField();
        btnHome = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlDeliveryRegister.setBackground(new java.awt.Color(204, 204, 255));

        lblDelReg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cooltext165385488635741.png"))); // NOI18N

        lblDateTime.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblDateTime.setText("Date and Time");

        lblDelAdd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblDelAdd.setText("Delivery address");

        lblNameRec.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNameRec.setText("Name of the recipient");

        btnRegDel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnRegDel.setText("Register delivery");

        tblDelReg.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Date and Time", "Delivery address", "Name of the recipient", "Cel"
            }
        ));
        jspDelReg.setViewportView(tblDelReg);

        javax.swing.GroupLayout pnlDeliveryLayout = new javax.swing.GroupLayout(pnlDelivery);
        pnlDelivery.setLayout(pnlDeliveryLayout);
        pnlDeliveryLayout.setHorizontalGroup(
            pnlDeliveryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDeliveryLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jspDelReg, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlDeliveryLayout.setVerticalGroup(
            pnlDeliveryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDeliveryLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jspDelReg, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        lblNameRec1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNameRec1.setText("Telephone number");

        txtNameRec1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameRec1ActionPerformed(evt);
            }
        });

        btnHome.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnHome.setText("Home");

        javax.swing.GroupLayout pnlDeliveryRegisterLayout = new javax.swing.GroupLayout(pnlDeliveryRegister);
        pnlDeliveryRegister.setLayout(pnlDeliveryRegisterLayout);
        pnlDeliveryRegisterLayout.setHorizontalGroup(
            pnlDeliveryRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDeliveryRegisterLayout.createSequentialGroup()
                .addGroup(pnlDeliveryRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDeliveryRegisterLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(pnlDeliveryRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNameRec)
                            .addComponent(lblDelAdd)
                            .addComponent(lblDateTime)
                            .addComponent(lblNameRec1))
                        .addGap(18, 18, 18)
                        .addGroup(pnlDeliveryRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtNameRec, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                            .addComponent(txtDelAdd, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDateTime, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNameRec1))
                        .addGap(39, 39, 39)
                        .addComponent(pnlDelivery, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlDeliveryRegisterLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(btnRegDel)
                        .addGap(0, 548, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(pnlDeliveryRegisterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnHome)
                .addGap(41, 41, 41)
                .addComponent(lblDelReg)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlDeliveryRegisterLayout.setVerticalGroup(
            pnlDeliveryRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDeliveryRegisterLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDeliveryRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDelReg)
                    .addComponent(btnHome))
                .addGroup(pnlDeliveryRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDeliveryRegisterLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(pnlDeliveryRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDateTime)
                            .addComponent(txtDateTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(pnlDeliveryRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDelAdd)
                            .addComponent(txtDelAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(pnlDeliveryRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNameRec)
                            .addComponent(txtNameRec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(pnlDeliveryRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNameRec1)
                            .addComponent(txtNameRec1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlDeliveryRegisterLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(pnlDelivery, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(btnRegDel)
                .addGap(63, 63, 63))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlDeliveryRegister, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlDeliveryRegister, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameRec1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameRec1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameRec1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IntDeliveryRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IntDeliveryRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IntDeliveryRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IntDeliveryRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IntDeliveryRegister().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnRegDel;
    private javax.swing.JScrollPane jspDelReg;
    private javax.swing.JLabel lblDateTime;
    private javax.swing.JLabel lblDelAdd;
    private javax.swing.JLabel lblDelReg;
    private javax.swing.JLabel lblNameRec;
    private javax.swing.JLabel lblNameRec1;
    private javax.swing.JPanel pnlDelivery;
    private javax.swing.JPanel pnlDeliveryRegister;
    private javax.swing.JTable tblDelReg;
    private javax.swing.JTextField txtDateTime;
    private javax.swing.JTextField txtDelAdd;
    private javax.swing.JTextField txtNameRec;
    private javax.swing.JTextField txtNameRec1;
    // End of variables declaration//GEN-END:variables
}
