package com.lorengie.Interface;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author ASUS_
 */
public class IntSalesRegister extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz3
     */
    public IntSalesRegister() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grpType = new javax.swing.ButtonGroup();
        pnlSalesRegister = new javax.swing.JPanel();
        lblProdCod = new javax.swing.JLabel();
        lblProdName = new javax.swing.JLabel();
        lblProdDesc = new javax.swing.JLabel();
        lblQuanProd = new javax.swing.JLabel();
        btnHome = new javax.swing.JButton();
        btnSendProd = new javax.swing.JButton();
        btnRemProd = new javax.swing.JButton();
        PnlSales = new javax.swing.JPanel();
        jspSalesRegis = new javax.swing.JScrollPane();
        tblSalesRegister = new javax.swing.JTable();
        btnAddSale = new javax.swing.JButton();
        btnPrintRec = new javax.swing.JButton();
        txtProdCod = new javax.swing.JTextField();
        txtProdName = new javax.swing.JTextField();
        txtProdDesc = new javax.swing.JTextField();
        txtQuanProd = new javax.swing.JTextField();
        lblSalesRegister = new javax.swing.JLabel();
        txtProducValue = new javax.swing.JTextField();
        lblProductValue = new javax.swing.JLabel();
        radDirectoSell = new javax.swing.JRadioButton();
        radHomeDelivery = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlSalesRegister.setBackground(new java.awt.Color(204, 204, 255));

        lblProdCod.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblProdCod.setText("Product code");

        lblProdName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblProdName.setText("Product name");

        lblProdDesc.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblProdDesc.setText("Product description");

        lblQuanProd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblQuanProd.setText("Quantity of the product");

        btnHome.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnHome.setText("Home");

        btnSendProd.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnSendProd.setText("Send product");

        btnRemProd.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnRemProd.setText("Remove product");

        tblSalesRegister.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Product", "Quantity", "Total Cost"
            }
        ));
        jspSalesRegis.setViewportView(tblSalesRegister);

        btnAddSale.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAddSale.setText("Add sale");

        btnPrintRec.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnPrintRec.setText("Print receipt");
        btnPrintRec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintRecActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PnlSalesLayout = new javax.swing.GroupLayout(PnlSales);
        PnlSales.setLayout(PnlSalesLayout);
        PnlSalesLayout.setHorizontalGroup(
            PnlSalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlSalesLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(btnAddSale)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPrintRec)
                .addContainerGap(42, Short.MAX_VALUE))
            .addGroup(PnlSalesLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jspSalesRegis, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        PnlSalesLayout.setVerticalGroup(
            PnlSalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlSalesLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jspSalesRegis, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(PnlSalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddSale)
                    .addComponent(btnPrintRec))
                .addGap(54, 54, 54))
        );

        lblSalesRegister.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cooltext165362721558039.png"))); // NOI18N

        txtProducValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProducValueActionPerformed(evt);
            }
        });

        lblProductValue.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblProductValue.setText("Product Value");

        grpType.add(radDirectoSell);
        radDirectoSell.setText("Direct sell");

        grpType.add(radHomeDelivery);
        radHomeDelivery.setText("Home delivery");

        javax.swing.GroupLayout pnlSalesRegisterLayout = new javax.swing.GroupLayout(pnlSalesRegister);
        pnlSalesRegister.setLayout(pnlSalesRegisterLayout);
        pnlSalesRegisterLayout.setHorizontalGroup(
            pnlSalesRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSalesRegisterLayout.createSequentialGroup()
                .addGroup(pnlSalesRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlSalesRegisterLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(pnlSalesRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSendProd)
                            .addComponent(lblProdName)
                            .addComponent(lblProdCod)
                            .addComponent(lblProdDesc)
                            .addComponent(lblQuanProd)
                            .addComponent(lblProductValue)
                            .addComponent(radDirectoSell))
                        .addGroup(pnlSalesRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlSalesRegisterLayout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addGroup(pnlSalesRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnRemProd, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtProdCod)
                                    .addComponent(txtProdName)
                                    .addComponent(txtProdDesc)
                                    .addComponent(txtQuanProd)
                                    .addComponent(txtProducValue)))
                            .addGroup(pnlSalesRegisterLayout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(radHomeDelivery)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addComponent(PnlSales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlSalesRegisterLayout.createSequentialGroup()
                        .addGroup(pnlSalesRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlSalesRegisterLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnHome))
                            .addGroup(pnlSalesRegisterLayout.createSequentialGroup()
                                .addGap(144, 144, 144)
                                .addComponent(lblSalesRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlSalesRegisterLayout.setVerticalGroup(
            pnlSalesRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSalesRegisterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnHome)
                .addGap(5, 5, 5)
                .addComponent(lblSalesRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 19, Short.MAX_VALUE)
                .addGroup(pnlSalesRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlSalesRegisterLayout.createSequentialGroup()
                        .addGroup(pnlSalesRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblProdCod)
                            .addComponent(txtProdCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlSalesRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblProdName)
                            .addComponent(txtProdName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlSalesRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblProdDesc)
                            .addComponent(txtProdDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(pnlSalesRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblQuanProd)
                            .addComponent(txtQuanProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlSalesRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtProducValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblProductValue))
                        .addGap(18, 18, 18)
                        .addGroup(pnlSalesRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(radDirectoSell)
                            .addComponent(radHomeDelivery))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                        .addGroup(pnlSalesRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSendProd)
                            .addComponent(btnRemProd))
                        .addGap(43, 43, 43))
                    .addGroup(pnlSalesRegisterLayout.createSequentialGroup()
                        .addComponent(PnlSales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlSalesRegister, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlSalesRegister, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPrintRecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintRecActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPrintRecActionPerformed

    private void txtProducValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProducValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProducValueActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IntSalesRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IntSalesRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IntSalesRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IntSalesRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IntSalesRegister().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PnlSales;
    private javax.swing.JButton btnAddSale;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnPrintRec;
    private javax.swing.JButton btnRemProd;
    private javax.swing.JButton btnSendProd;
    private javax.swing.ButtonGroup grpType;
    private javax.swing.JScrollPane jspSalesRegis;
    private javax.swing.JLabel lblProdCod;
    private javax.swing.JLabel lblProdDesc;
    private javax.swing.JLabel lblProdName;
    private javax.swing.JLabel lblProductValue;
    private javax.swing.JLabel lblQuanProd;
    private javax.swing.JLabel lblSalesRegister;
    private javax.swing.JPanel pnlSalesRegister;
    private javax.swing.JRadioButton radDirectoSell;
    private javax.swing.JRadioButton radHomeDelivery;
    private javax.swing.JTable tblSalesRegister;
    private javax.swing.JTextField txtProdCod;
    private javax.swing.JTextField txtProdDesc;
    private javax.swing.JTextField txtProdName;
    private javax.swing.JTextField txtProducValue;
    private javax.swing.JTextField txtQuanProd;
    // End of variables declaration//GEN-END:variables
}
