package com.lorengie.Interface;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author ASUS_
 */
public class IntSearchProducts extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz4
     */
    public IntSearchProducts() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlSearchProducts = new javax.swing.JPanel();
        btnHome1 = new javax.swing.JButton();
        lblSearchProd = new javax.swing.JLabel();
        lblProdName1 = new javax.swing.JLabel();
        lblAvail = new javax.swing.JLabel();
        lblQuantity = new javax.swing.JLabel();
        lblLocation = new javax.swing.JLabel();
        txtProdName1 = new javax.swing.JTextField();
        txtAvail = new javax.swing.JTextField();
        txtQuan = new javax.swing.JTextField();
        txtLocation = new javax.swing.JTextField();
        pnlImage = new javax.swing.JPanel();
        lblImgSearchProd = new javax.swing.JLabel();
        btnSearchProd = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlSearchProducts.setBackground(new java.awt.Color(204, 204, 255));

        btnHome1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnHome1.setText("Home");

        lblSearchProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cooltext165379621404374.png"))); // NOI18N

        lblProdName1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblProdName1.setText("Product name");

        lblAvail.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblAvail.setText("Availability");

        lblQuantity.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblQuantity.setText("Quantity");

        lblLocation.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblLocation.setText("Location");

        txtProdName1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProdName1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlImageLayout = new javax.swing.GroupLayout(pnlImage);
        pnlImage.setLayout(pnlImageLayout);
        pnlImageLayout.setHorizontalGroup(
            pnlImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlImageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImgSearchProd, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlImageLayout.setVerticalGroup(
            pnlImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlImageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImgSearchProd, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnSearchProd.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnSearchProd.setText("Search Product");

        javax.swing.GroupLayout pnlSearchProductsLayout = new javax.swing.GroupLayout(pnlSearchProducts);
        pnlSearchProducts.setLayout(pnlSearchProductsLayout);
        pnlSearchProductsLayout.setHorizontalGroup(
            pnlSearchProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSearchProductsLayout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(pnlSearchProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlSearchProductsLayout.createSequentialGroup()
                        .addGroup(pnlSearchProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlSearchProductsLayout.createSequentialGroup()
                                .addGroup(pnlSearchProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblProdName1)
                                    .addComponent(lblAvail)
                                    .addComponent(lblQuantity)
                                    .addComponent(lblLocation))
                                .addGap(93, 93, 93)
                                .addGroup(pnlSearchProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtProdName1, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                                    .addComponent(txtAvail)
                                    .addComponent(txtQuan)
                                    .addComponent(txtLocation)))
                            .addGroup(pnlSearchProductsLayout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(btnSearchProd)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnlImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlSearchProductsLayout.createSequentialGroup()
                        .addComponent(lblSearchProd)
                        .addGap(0, 120, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(pnlSearchProductsLayout.createSequentialGroup()
                .addComponent(btnHome1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlSearchProductsLayout.setVerticalGroup(
            pnlSearchProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSearchProductsLayout.createSequentialGroup()
                .addComponent(btnHome1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSearchProd)
                .addGroup(pnlSearchProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlSearchProductsLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(pnlSearchProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtProdName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblProdName1))
                        .addGap(41, 41, 41)
                        .addGroup(pnlSearchProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAvail)
                            .addComponent(txtAvail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49)
                        .addGroup(pnlSearchProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblQuantity)
                            .addComponent(txtQuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addGroup(pnlSearchProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblLocation)
                            .addComponent(txtLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSearchProd))
                    .addGroup(pnlSearchProductsLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(pnlImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(3, 43, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlSearchProducts, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlSearchProducts, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtProdName1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProdName1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProdName1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IntSearchProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IntSearchProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IntSearchProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IntSearchProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IntSearchProducts().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHome1;
    private javax.swing.JButton btnSearchProd;
    private javax.swing.JLabel lblAvail;
    private javax.swing.JLabel lblImgSearchProd;
    private javax.swing.JLabel lblLocation;
    private javax.swing.JLabel lblProdName1;
    private javax.swing.JLabel lblQuantity;
    private javax.swing.JLabel lblSearchProd;
    private javax.swing.JPanel pnlImage;
    private javax.swing.JPanel pnlSearchProducts;
    private javax.swing.JTextField txtAvail;
    private javax.swing.JTextField txtLocation;
    private javax.swing.JTextField txtProdName1;
    private javax.swing.JTextField txtQuan;
    // End of variables declaration//GEN-END:variables
}
