package com.lorengie.Interface;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author ASUS_
 */
public class IntSeller extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz6
     */
    public IntSeller() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlSeller = new javax.swing.JPanel();
        lblLorengieSupe = new javax.swing.JLabel();
        lblImgRegSal = new javax.swing.JLabel();
        lblImgSearProd = new javax.swing.JLabel();
        btnRegSal = new javax.swing.JButton();
        btnSearProd = new javax.swing.JButton();
        lblSeller = new javax.swing.JLabel();
        lblImgSeller = new javax.swing.JLabel();
        lblImage = new javax.swing.JLabel();
        lblAddImg = new javax.swing.JLabel();
        btnAddProdToInven = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlSeller.setBackground(new java.awt.Color(204, 204, 255));

        lblLorengieSupe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cooltext165357678840369.png"))); // NOI18N

        lblImgRegSal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/register.png"))); // NOI18N

        lblImgSearProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/search.png"))); // NOI18N

        btnRegSal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnRegSal.setText("Register sales");

        btnSearProd.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnSearProd.setText("Search products");

        lblSeller.setText("Seller");

        lblImage.setText("Im");

        lblAddImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/addInventory.png"))); // NOI18N

        btnAddProdToInven.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnAddProdToInven.setText("Add Product to Inventory");

        javax.swing.GroupLayout pnlSellerLayout = new javax.swing.GroupLayout(pnlSeller);
        pnlSeller.setLayout(pnlSellerLayout);
        pnlSellerLayout.setHorizontalGroup(
            pnlSellerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSellerLayout.createSequentialGroup()
                .addGroup(pnlSellerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlSellerLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(pnlSellerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblImgRegSal, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRegSal))
                        .addGap(77, 77, 77)
                        .addGroup(pnlSellerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSearProd)
                            .addGroup(pnlSellerLayout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(lblImgSearProd, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(pnlSellerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlSellerLayout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(btnAddProdToInven))
                            .addGroup(pnlSellerLayout.createSequentialGroup()
                                .addGap(138, 138, 138)
                                .addComponent(lblAddImg))))
                    .addGroup(pnlSellerLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(lblLorengieSupe)
                        .addGap(99, 99, 99)
                        .addComponent(lblSeller)
                        .addGap(56, 56, 56)
                        .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(7, 7, Short.MAX_VALUE)
                .addComponent(lblImgSeller))
        );
        pnlSellerLayout.setVerticalGroup(
            pnlSellerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSellerLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lblImgSeller)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlSellerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlSellerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblSeller))
                    .addComponent(lblLorengieSupe))
                .addGroup(pnlSellerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlSellerLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(pnlSellerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblImgRegSal, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblImgSearProd, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlSellerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnRegSal)
                            .addComponent(btnSearProd)
                            .addComponent(btnAddProdToInven, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlSellerLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(lblAddImg)))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlSeller, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlSeller, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IntSeller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IntSeller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IntSeller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IntSeller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IntSeller().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddProdToInven;
    private javax.swing.JButton btnRegSal;
    private javax.swing.JButton btnSearProd;
    private javax.swing.JLabel lblAddImg;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblImgRegSal;
    private javax.swing.JLabel lblImgSearProd;
    private javax.swing.JLabel lblImgSeller;
    private javax.swing.JLabel lblLorengieSupe;
    private javax.swing.JLabel lblSeller;
    private javax.swing.JPanel pnlSeller;
    // End of variables declaration//GEN-END:variables
}
